### ISSUE TITLE
Pull in 0.3.30 of java-spring-boot2 stack

### ISSUE THREAD

**Issue by scottkurz** [icp4apps/stack-hub#27]
Once v0.3.30 is built and released, update https://github.com/icp4apps/stack-hub/blob/master/config/appsody_stack_config.yaml to pull it in.

I'm not clear what the release part of the URL will be, 
e.g. the "0.9.0" in  https://github.com/kabanero-io/collections/releases/download/0.9.0/java-spring-boot2-0.3.29-index.yaml  or would submit the PR now.

**Comment by scottkurz** [comment]
@garypicher

**Comment by jgawor** [comment]
Done in https://github.com/icp4apps/stack-hub/pull/28/
