### ISSUE TITLE
Suggested README updates

### ISSUE THREAD

**Issue by SueChaplain** [icp4apps/stack-hub#5]
1. The link to the devfile example configuration file is broken (missing "v" in devfile)
2. The Appsody example config file references Java microprofile, which is now deprecated. Might be worth replacing with something else to avoid confusion. The title also says "# Sample configuration for Kabanero stack hub" ..Maybe should say IBM Cloud Pak for Applications stack hub"?
3. The README title is REPO-TOOLS. Should this be updated?
4. I think the Appsody stack config in the README has incorrect indentation for `include:`

**Comment by jgawor** [comment]
All of these should be addressed already or in #8.
